DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER (
    uId VARCHAR(30) NOT NULL,
    uPw VARCHAR(30) NOT NULL,
    uEmail VARCHAR(50) NOT NULL,
    uPhoneNumber VARCHAR(50),
    PRIMARY KEY (uId)
);

SELECT * FROM MEMBER;
